### PR TITLE
Support NSwag JSON schema types and formats

### PR DESCRIPTION
**Pull request by bricelam**
See https://github.com/RicoSuter/NJsonSchema/blob/dde6f76a80b8acd55ff4f51e04c77b6b742f4294/src/NJsonSchema/Generation/ReflectionServiceBase.cs#L69

### CODE REVIEW

**Comment by bricelam** [comment]
Yikes, not sure why GitHub made all the whitespace changes. Be sure to [Hide whitespace](https://github.com/microsoft/Power-Fx/pull/2749/files?w=1)

**Comment by bricelam** [comment]
@microsoft-github-policy-service agree

**Comment by MikeStall** [comment]
> Yikes, not sure why GitHub made all the whitespace changes. Be sure to [Hide whitespace](https://github.com/microsoft/Power-Fx/pull/2749/files?w=1)

Can you submit without the whitespace? 
It's probably an auto-format feature in your editor. 

The thing is the whitespace touches lots of lines, which can interfere with git blame and viewing history.

**Review by LucGenetier — APPROVED** [review]
:shipit:

**Comment by LucGenetier** [comment]
Looks like it doesn't compile
src\libraries\Microsoft.PowerFx.Connectors\OpenApiExtensions.cs(712,17): Error CS0152: The switch statement contains multiple cases with the label value '"file"'

**Comment by bricelam** [comment]
Updated. The file case has already been fixed since 1.2.0

**Review by LucGenetier — APPROVED** [review]

**Pull request merged**
