### PR TITLE
Fix scope info for AddColumns / Search functions

### PR DESCRIPTION
**Pull request by CarlosFigueiraMSFT**
The ScopeInfo declaration for the Search and AddColumn functions was incorrectly being applied to all arguments; it should only be applied to the ones that represent column names.

### CODE REVIEW

**Review by lesaltzm — DISMISSED** [review]

**Comment by lesaltzm** [comment]
Also RenameColumns (only existing names are in scope)

**Review by lesaltzm — APPROVED** [review]
🚢

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by lesaltzm — APPROVED** [review]

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
