### PR TITLE
Fixes IfError under V1 flag

### LINKED ISSUE #1173: Review IfError()'s CheckType() and add void type support.
`IfError()` has buggy implementation of CheckType(),

e.g. 
below expression should be an error:
`IfError(1, {x:1}, {x:1}, {y:1}, 1)` Since it can potentially return a record or a number type

In both cases, it should have been consistent, since the possible result type can be either Number or Time type for both the expression and should have been super typed to the same thing...
`IfError(1, 1, Time(12,0,0)) => Time Type` 
`IfError(1, Time(12,0,0)) => Number Type`

-Also add void type support for mismatched args.

### PR DESCRIPTION
**Pull request by jas-valgotar**
- Followup to https://github.com/microsoft/Power-Fx/pull/1230
- Fixes #1173

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by lesaltzm — APPROVED** [review]

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by Shpakh-MSFT — APPROVED** [review]
:shipit:

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
