### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by LucGenetier**
Remove HasField and HadFieldLogical APIs
Those aren't used by PA Client

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by MikeStall — APPROVED** [review]

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
