### PR TITLE
Excel Compat: Remove ConsistentOneColumnTableResult flag

### PR DESCRIPTION
**Pull request by Ananya-Gupta24**
As part of the excel compatibility work, all tabular overloads of functions will return "Value" as the output column name instead of the varying names returned currently ("Result" or input column name). This PR removes the flag and enables this behavior by default. Test updates included. 
This change will go in as part of a PowerFx version update to be added in this PAClient [PR](https://msazure.visualstudio.com/OneAgile/_git/PowerApps-Client/pullrequest/7341719) to ensure that there is no breakage.

### CODE REVIEW

**Comment by Ananya-Gupta24** [comment]
Won't be checked in till [PAClient PR](https://msazure.visualstudio.com/OneAgile/_git/PowerApps-Client/pullrequest/7341719) is ready

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by lesaltzm** [comment]
We can't remove flags that have back compat impact. Discussed offline.

**Review by lesaltzm — CHANGES_REQUESTED** [review]
See above, marking as request change to  ensure this is never checked in.

**Pull request closed without merging**
