### PR TITLE
Reviewed and updated some overrides test files

### PR DESCRIPTION
**Pull request by gregli-msft**
Resolved https://github.com/microsoft/Power-Fx/issues/978.  After this PR, all overrides are understood with a couple being fixed by an upcoming Carlos Blank handling PR.

This PR will require adding an override file to Canvas, which will be done separately.  Canvas is doing the wrong thing, the override should be there.

Finally, REPL updated to better handle Unicode characters.

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by CarlosFigueiraMSFT — APPROVED** [review]
:shipit:

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
