### PR TITLE
Add debug logging helpers

### PR DESCRIPTION
**Pull request by MikeStall**
Add new DebugDump* methods which can log SymbolTable, SymbolValues. 

This can help with debugging to provide visibility for these.  (like a text-based visualizer ... eventually ... https://learn.microsoft.com/en-us/visualstudio/debugger/create-custom-visualizers-of-data?view=vs-2022 ) 

For example:
```
CheckResult

x + y

Binding: Number

IR:
BinaryOp(AddNumbers, ResolvedObject('x:FromRecord_55206300'), ResolvedObject('y:Globals_31639720'))

Symbols:
   SymbolTable '(FromRecord,Globals,BuiltinFunctions (149),DefaultConfig)_3776722', hash=1776687751
    Composed {
     SymbolTable 'FromRecord_55206300', hash=954974759
      x:n

     SymbolTable 'Globals_31639720', hash=954174782
      y:n

     SymbolTable 'BuiltinFunctions (149)_43315893', hash=954660935

```

### CODE REVIEW

**Review by anderson-joyle — DISMISSED** [review]
:shipit:

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by anderson-joyle — APPROVED** [review]
:shipit:

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
