### PR TITLE
Add Left/Right/Substitute tabular implementations to the interpreter

### PR DESCRIPTION
**Pull request by CarlosFigueiraMSFT**
Some functions that were missing in the interpreter

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by MikeStall — APPROVED** [review]

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
