### PR TITLE
Fix API compatibility script

### PR DESCRIPTION
**Pull request by LucGenetier**

### CODE REVIEW

**Comment by BruceHaley** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by BruceHaley** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:x: 2 Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes** compared against [version 0.2.3-preview.20221213-333319](https://www.nuget.org/packages/Microsoft.PowerFx.Transport.Attributes/0.2.3-preview.20221213-333319).
<details>

```
MembersMustExist : Member 'Microsoft.AppMagic.Transport.TransportConverterAttribute..ctor(System.Type, System.Type, System.String, System.String, System.String, System.String, System.String, System.String)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'Microsoft.AppMagic.Transport.TransportDisabledAttribute..ctor()' does not exist in the implementation but it does exist in the contract.
```

</details>

**Comment by LucGenetier** [comment]
Public API changes: ❌CP0002 M:Microsoft.AppMagic.Transport.TransportConverterAttribute.#ctor(System.Type,System.Type,System.String,System.String,System.String,System.String,System.String,System.String)<br />❌CP0002 M:Microsoft.AppMagic.Transport.TransportDisabledAttribute.#ctor

**Comment by LucGenetier** [comment]
Public API changes: <br />❌CP0002 M:Microsoft.AppMagic.Transport.TransportConverterAttribute.#ctor(System.Type,System.Type,System.String,System.String,System.String,System.String,System.String,System.String)<br />❌CP0002 M:Microsoft.AppMagic.Transport.TransportDisabledAttribute.#ctor

**Comment by BruceHaley** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:x: 2 Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes** compared against [version 0.2.3-preview.20221213-333319](https://www.nuget.org/packages/Microsoft.PowerFx.Transport.Attributes/0.2.3-preview.20221213-333319).
<details>

```
MembersMustExist : Member 'Microsoft.AppMagic.Transport.TransportConverterAttribute..ctor(System.Type, System.Type, System.String, System.String, System.String, System.String, System.String, System.String)' does not exist in the implementation but it does exist in the contract.
MembersMustExist : Member 'Microsoft.AppMagic.Transport.TransportDisabledAttribute..ctor()' does not exist in the implementation but it does exist in the contract.
```

</details>

**Comment by BruceHaley** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by MikeStall — APPROVED** [review]

**Comment by BruceHaley** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
