### PR TITLE
Allow for display name refresh when cloning and rebinding UDF

### PR DESCRIPTION
**Pull request by rick-nguyen**
This is needed for datasource display name changes if a parameter of the UDF is a datasource type.

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by adithyaselv — DISMISSED** [review]
Looks good. please fix the doc string

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by adithyaselv — APPROVED** [review]
Please change the PR title before merging

**Pull request merged**
