### PR TITLE
Implement EncodeHTML function

### PR DESCRIPTION
**Pull request by CarlosFigueiraMSFT**
We already have a way to encode URL data with the EncodeUrl function, this adds the capability to do the same with HTML data.

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by anderson-joyle** [comment]
What exactly are we breaking with this new function?

**Comment by CarlosFigueiraMSFT** [comment]
> What exactly are we breaking with this new function?

Nothing. But we need to have it implemented in Power Apps before we can complete this PR, as the function is being added to the list of core functions.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by adithyaselv — APPROVED** [review]
:shipit:

**Pull request merged**
