### PR TITLE
Added new method on IExternalRule to help with invariantexpression ch…

### PR DESCRIPTION
**Pull request by Shpakh-MSFT**
On an effort to remove null rule binding, we need the ability to have an option to apply null binding before doing the check if binding is null. This change adds a new method on IExternalRule to help with that.

### CODE REVIEW

**Review by lesaltzm — APPROVED** [review]
.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by lesaltzm — APPROVED** [review]

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
