### PR TITLE
Update order of checking for scoping variable during binder's visit of FirstName

### PR DESCRIPTION
**Pull request by CarlosFigueiraMSFT**
For an expression such as `With({a:1}, Set(a, 10))`, the first argument of the Set function should not refer to the scope variable `a` defined by the With function.

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by anderson-joyle** [comment]
What's the expected result of `With({a:1}, Set(a, 10); a + 1)`?

**Comment by CarlosFigueiraMSFT** [comment]
> What's the expected result of `With({a:1}, Set(a, 10); a + 1)`?

It will be 11; the `a` in the Set call will not be bound to the scope from With

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by lesaltzm — APPROVED** [review]

**Pull request merged**
