### PR TITLE
Fix check of FirstN/LastN functions with new feature flag

### PR DESCRIPTION
**Pull request by CarlosFigueiraMSFT**
Check for validity of calls to the FirstN/LastN function with the new feature flag that requires two arguments was broken. This fixes it.

### CODE REVIEW

**Comment by Shpakh-MSFT** [comment]
>                   1,

Shouldn't be MinArity be 2 as well if context.Features.FirstLastNRequiresSecondArguments true?

---
Refers to: src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/FirstLastN.cs:30 in 7d403ec. [](commit_id = 7d403ecf5795e4c95ea9ab167ea6fb858fde494a, deletion_comment = False)

**Comment by CarlosFigueiraMSFT** [comment]
>                   1,

We don't have the context at this point

---
In reply to: [1500329853](https://github.com/microsoft/Power-Fx/pull/1324#issuecomment-1500329853) [](http://example.com/codeflow?ancestors=1500329853,1500329853)

---
Refers to: src/libraries/Microsoft.PowerFx.Core/Texl/Builtins/FirstLastN.cs:30 in 7d403ec. [](commit_id = 7d403ecf5795e4c95ea9ab167ea6fb858fde494a, deletion_comment = False)

**Review by Shpakh-MSFT — APPROVED** [review]
:shipit:

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
