### PR TITLE
Ensured consistent error messages (Issue #529)

### LINKED ISSUE #529: Ensure consistent error messages
Ensure the error Messages are constentn. 

For example:
`IfError(Text(1/0), FirstError.Message)`

In PowerApps:
"Invalid operation: division by zero."

In Power Fx Interpreter:
"Divide by zero"

### PR DESCRIPTION
**Pull request by jas-valgotar**
- Updated the message
- Added the test for the same
- Fixes #529

### CODE REVIEW

**Comment by BruceHaley** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

**Comment by MikeStall** [comment]
We'll leave this issue as a one-off fix, and we'll use #548 to track the broader issue of proper localization support.

**Review by MikeStall — APPROVED** [review]
:shipit:

**Comment by BruceHaley** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Core.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

**Pull request merged**
