### PR TITLE
[[Power-Fx]] Localization hand-back [CTAS - RunID=20230523-161854-qsjwm932b4]

### PR DESCRIPTION
**Pull request by toshio-msft**
Translation handback check-in (PR Created by automation).

### CODE REVIEW

**Review by lesaltzm — APPROVED** [review]

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by LucGenetier — APPROVED** [review]

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
