### PR TITLE
TexlFunction clean-up: inlining, screen dependency, used in tests

### PR DESCRIPTION
**Pull request by CarlosFigueiraMSFT**
The following virtuals from TexlFunction are only used in Power Apps, and do not make sense in Power Fx:

- SupportsInlining: this is a platform-dependent feature
- CreatesImplicitScreenDependency: no core functions use it
- CanBeUsedInTests: platform-dependent feature
- CanSuggestThisItem: related to galleries, a Power Apps feature

This PR removes them, and will update Power Apps to move that logic there later.

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by Shpakh-MSFT** [comment]
>         public virtual bool IsTestOnly => false;

How about this one?

---
Refers to: src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs:158 in c9d0d8c. [](commit_id = c9d0d8c13d62b87a6f1524656f50bea2e070e91a, deletion_comment = False)

**Comment by Shpakh-MSFT** [comment]
>         public virtual bool RequiresBindingContext => false;

This one too?

---
Refers to: src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs:188 in c9d0d8c. [](commit_id = c9d0d8c13d62b87a6f1524656f50bea2e070e91a, deletion_comment = False)

**Comment by CarlosFigueiraMSFT** [comment]
>         public virtual bool RequiresBindingContext => false;

This one has a bigger impact in PAClient, will remove it separately

---
In reply to: [1446481486](https://github.com/microsoft/Power-Fx/pull/1115#issuecomment-1446481486) [](http://example.com/codeflow?ancestors=1446481486,1446481486)

---
Refers to: src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs:188 in c9d0d8c. [](commit_id = c9d0d8c13d62b87a6f1524656f50bea2e070e91a, deletion_comment = False)

**Comment by CarlosFigueiraMSFT** [comment]
>         public virtual bool IsTestOnly => false;

I want to discuss about this one, not sure if we want to have a concept of testing for Power Fx

---
In reply to: [1446478280](https://github.com/microsoft/Power-Fx/pull/1115#issuecomment-1446478280) [](http://example.com/codeflow?ancestors=1446478280,1446478280)

---
Refers to: src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs:158 in c9d0d8c. [](commit_id = c9d0d8c13d62b87a6f1524656f50bea2e070e91a, deletion_comment = False)

**Comment by CarlosFigueiraMSFT** [comment]
>         public virtual bool CanSuggestThisItem => false;

Probably

---
In reply to: [1446480505](https://github.com/microsoft/Power-Fx/pull/1115#issuecomment-1446480505) [](http://example.com/codeflow?ancestors=1446480505,1446480505)

---
Refers to: src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs:170 in c9d0d8c. [](commit_id = c9d0d8c13d62b87a6f1524656f50bea2e070e91a, deletion_comment = False)

**Comment by CarlosFigueiraMSFT** [comment]
>         public virtual bool IsTestOnly => false;

Removed it since this class is internal.

---
In reply to: [1446486180](https://github.com/microsoft/Power-Fx/pull/1115#issuecomment-1446486180) [](http://example.com/codeflow?ancestors=1446486180,1446478280)

---
Refers to: src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs:158 in c9d0d8c. [](commit_id = c9d0d8c13d62b87a6f1524656f50bea2e070e91a, deletion_comment = False)

**Comment by CarlosFigueiraMSFT** [comment]
>         public virtual bool IsTestOnly => false;

"Unremoved" it. It's used in the binder. We should still remove it, but we'll do it later.

---
In reply to: [1450582236](https://github.com/microsoft/Power-Fx/pull/1115#issuecomment-1450582236) [](http://example.com/codeflow?ancestors=1450582236,1446486180,1446478280)

---
Refers to: src/libraries/Microsoft.PowerFx.Core/Functions/TexlFunction.cs:158 in c9d0d8c. [](commit_id = c9d0d8c13d62b87a6f1524656f50bea2e070e91a, deletion_comment = False)

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by Shpakh-MSFT — APPROVED** [review]
:shipit:

**Pull request merged**
