### PR TITLE
Removes KnownTableType, makes TableType sealed.

### PR DESCRIPTION
**Pull request by lesaltzm**
All tables are tables of records. Requiring lazy types to choose whether
they derive from TableType or RecordType is unnecessary confusion, and
instead, they should always derive from RecordType, calling ToTable if
needed as a table.

### CODE REVIEW

**Comment by BruceHaley** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:x: 4 Binary Compatibility issues for **Microsoft.PowerFx.Core** compared against [version 0.2.2-preview.20220815-317077](https://www.nuget.org/packages/Microsoft.PowerFx.Core/0.2.2-preview.20220815-317077).
<details>

```
CannotSealType : Type 'Microsoft.PowerFx.Types.TableType' is actually (has the sealed modifier) sealed in the implementation but not sealed in the contract.
MembersMustExist : Member 'Microsoft.PowerFx.Types.TableType..ctor()' does not exist in the implementation but it does exist in the contract.
CannotMakeMemberNonVirtual : Member 'Microsoft.PowerFx.Types.TableType.Add(Microsoft.PowerFx.Types.NamedFormulaType)' is non-virtual in the implementation but is virtual in the contract.
CannotMakeMemberNonVirtual : Member 'Microsoft.PowerFx.Types.TableType.Visit(Microsoft.PowerFx.Types.ITypeVisitor)' is non-virtual in the implementation but is virtual in the contract.
```

</details>
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

**Comment by MikeStall** [comment]
This should solve #550

**Review by MikeStall — APPROVED** [review]
:shipit:

**Comment by BruceHaley** [comment]
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Connectors.dll**
:x: 4 Binary Compatibility issues for **Microsoft.PowerFx.Core** compared against [version 0.2.2-preview.20220815-317110](https://www.nuget.org/packages/Microsoft.PowerFx.Core/0.2.2-preview.20220815-317110).
<details>

```
CannotSealType : Type 'Microsoft.PowerFx.Types.TableType' is actually (has the sealed modifier) sealed in the implementation but not sealed in the contract.
MembersMustExist : Member 'Microsoft.PowerFx.Types.TableType..ctor()' does not exist in the implementation but it does exist in the contract.
CannotMakeMemberNonVirtual : Member 'Microsoft.PowerFx.Types.TableType.Add(Microsoft.PowerFx.Types.NamedFormulaType)' is non-virtual in the implementation but is virtual in the contract.
CannotMakeMemberNonVirtual : Member 'Microsoft.PowerFx.Types.TableType.Visit(Microsoft.PowerFx.Types.ITypeVisitor)' is non-virtual in the implementation but is virtual in the contract.
```

</details>
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Interpreter.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.LanguageServerProtocol.dll**
:heavy_check_mark: No Binary Compatibility issues for **Microsoft.PowerFx.Transport.Attributes.dll**

**Pull request merged**
