### PR TITLE
Fix: Null Handling in NodeKind Intellisense

### PR DESCRIPTION
**Pull request by adithyaselv**
CurNode in IntellisenseData can be Null in different scenarios and we have a NullNodeIntellisense Handler for this specific reason which suggests global/ in scope Values  , However this may not be applicable to all the cases such as suggesting types for UDF.

Not handling null here forces us to have a very strict order in running intellisense handlers , otherwise raising an exception which leads to no Intellisense results.

It is safe for us to assume CurNode could be null and skip the current suggestion handler instead of throwing an exception.

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by Shpakh-MSFT — DISMISSED** [review]

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by rick-nguyen — APPROVED** [review]

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
