### PR TITLE
Change Error Span for "Function X has some invalid arguments"

### PR DESCRIPTION
**Pull request by lesaltzm**
Moves the error span for "some invalid arguments" to just the head of the call node, so it doesn't hide/distract from other more specific errors in the formula bar

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by CarlosFigueiraMSFT — APPROVED** [review]
:shipit:

**Comment by lesaltzm** [comment]
Do not merge, pending test in PA Client

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
