### PR TITLE
Do not throw while serializing unsupported type in legacy serializer. Useful for Intellisense…

### LINKED ISSUE #1728: LSP: PublishExpressionType for unhandled types
In LSP, PublishExpressionType  will try to serialize the type. This can fail for unsupported types. We should handle gracefully at `Microsoft.PowerFx.LanguageServerProtocol.LanguageServer.PublishExpressionType()` , not as an unhandled exception. 

System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.Visit(UnsupportedType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.GetChildren(AggregateType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.Visit(TableType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.GetChildren(AggregateType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.Visit(TableType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.GetChildren(AggregateType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.Visit(TableType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.GetChildren(AggregateType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.Visit(TableType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.GetChildren(AggregateType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.Visit(TableType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.GetChildren(AggregateType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.Visit(TableType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.GetChildren(AggregateType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.FormulaTypeToSchemaVisitor.Visit(RecordType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeToSchemaConverter.Convert(FormulaType type)
   at Microsoft.PowerFx.LanguageServerProtocol.FormulaTypeJsonConverter.Write(Utf8JsonWriter writer, FormulaType value, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWriteAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Microsoft.PowerFx.LanguageServerProtocol.LanguageServer.PublishExpressionType(String documentUri, CheckResult result)

### PR DESCRIPTION
**Pull request by jas-valgotar**
Fixes #1728

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by MikeStall — APPROVED** [review]
:shipit:

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
