### PR TITLE
remove obsolete surface

### PR DESCRIPTION
**Pull request by MikeStall**
Sweeping for GA, remove public obsolete APIs.

### CODE REVIEW

**Comment by LucGenetier** [comment]
Public API changes: <br />❌CP0001 T:Microsoft.PowerFx.IUserInfo<br />❌CP0001 T:Microsoft.PowerFx.SymbolTableExtensionsCP0002 M:Microsoft.PowerFx.RecalcEngine.DefineType(System.String,Microsoft.PowerFx.ParserOptions)

**Review by jas-valgotar — APPROVED** [review]
:shipit:

**Comment by LucGenetier** [comment]
Public API changes: <br />❌CP0001 T:Microsoft.PowerFx.IUserInfo<br />❌CP0001 T:Microsoft.PowerFx.SymbolTableExtensionsCP0002 M:Microsoft.PowerFx.RecalcEngine.DefineType(System.String,Microsoft.PowerFx.ParserOptions)

**Comment by LucGenetier** [comment]
Public API changes: <br />❌CP0001 T:Microsoft.PowerFx.IUserInfo<br />❌CP0001 T:Microsoft.PowerFx.SymbolTableExtensionsCP0002 M:Microsoft.PowerFx.RecalcEngine.DefineType(System.String,Microsoft.PowerFx.ParserOptions)

**Pull request merged**
