### PR TITLE
Add Field to Nl2Fx and Fx2Nl Result Dtos to hold diagnostics info such as Model prompt

### PR DESCRIPTION
**Pull request by akshar2401**
This pr simply adds a new field to capture diagnostics for fx2nl or nl2fx

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by MikeStall — APPROVED** [review]
:shipit:

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
