### PR TITLE
Binder should suggest based on "AllowSideEffects"

### PR DESCRIPTION
**Pull request by anderson-joyle**
Issue https://github.com/microsoft/Power-Fx/issues/2304.

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by anderson-joyle** [comment]
> > ```
> >     [InlineData("Patch(table2,|", "record2")]
> > ```
> 
> Since we are not in a behavior context here (i.e., allowSideEffect = false), should we suggest this record?
> 
> Refers to: src/tests/Microsoft.PowerFx.Interpreter.Tests/InterpreterSuggestTests.cs:224 in [2d2aeca](https://github.com/microsoft/Power-Fx/commit/2d2aecac3876686665be56a26c5f0b24b445cd33). [](commit_id = [2d2aeca](https://github.com/microsoft/Power-Fx/commit/2d2aecac3876686665be56a26c5f0b24b445cd33), deletion_comment = False)

This is a good question. In this context, the only possible overload will be `Patch(record, record, ...)`. The first argument is wrong, but the engine would still suggest a good `argN`.

**Review by CarlosFigueiraMSFT — APPROVED** [review]
:shipit:

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
