### PR TITLE
Refactor tabular tests for PAClient runner

### PR DESCRIPTION
**Pull request by Ananya-Gupta24**
As part of the excel compat work, tabular overloads of functions will return "Value" as the output column name. This PR just refactors tabular test coverage so that all tests with the old behavior are consolidated under exclusive files.

- ArgCoercionT.txt
- CharT.txt
- ConcatenateT.txt
- Distinct.txt
- ExpT.txt
- FindT.txt
- LenT.txt
- LnT.txt
- RoundTable.txt
- Split.txt
- SqrtT.txt
- TabularOverloadsBlanksAndErrorsT.txt
- TableStringfuncsT.txt

The _ConsistentOneColumnResult versions cover the same test cases as these files, but with the new behavior (Value as output column name).

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by CarlosFigueiraMSFT** [comment]
> // *********** 2+-argument functions, errors ***********

Do we need a _ConsistentOneColumnResult version of this test?

---
Refers to: src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TabularOverloadsBlanksAndErrorsT.txt:1 in 0d0f1a7. [](commit_id = 0d0f1a72217b16c8436ea8d5f366c37fae491fe3, deletion_comment = False)

**Comment by CarlosFigueiraMSFT** [comment]
> // Scalar + Table

Do we need a _ConsistentOneColumnResult version of this test?

---
Refers to: src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TableStringfuncsT.txt:1 in 0d0f1a7. [](commit_id = 0d0f1a72217b16c8436ea8d5f366c37fae491fe3, deletion_comment = False)

**Comment by Ananya-Gupta24** [comment]
> > // *********** 2+-argument functions, errors ***********
> 
> Do we need a _ConsistentOneColumnResult version of this test?
> 
> Refers to: src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TabularOverloadsBlanksAndErrorsT.txt:1 in [0d0f1a7](https://github.com/microsoft/Power-Fx/commit/0d0f1a72217b16c8436ea8d5f366c37fae491fe3). [](commit_id = [0d0f1a7](https://github.com/microsoft/Power-Fx/commit/0d0f1a72217b16c8436ea8d5f366c37fae491fe3), deletion_comment = False)

The _ConsistentOneColumnResult [version](https://github.com/microsoft/Power-Fx/blob/main/src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TrigTableFunctions_ConsistentOneColumnTableResult.txt) already exists

**Comment by Ananya-Gupta24** [comment]
> > // Scalar + Table
> 
> Do we need a _ConsistentOneColumnResult version of this test?
> 
> Refers to: src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TableStringfuncsT.txt:1 in [0d0f1a7](https://github.com/microsoft/Power-Fx/commit/0d0f1a72217b16c8436ea8d5f366c37fae491fe3). [](commit_id = [0d0f1a7](https://github.com/microsoft/Power-Fx/commit/0d0f1a72217b16c8436ea8d5f366c37fae491fe3), deletion_comment = False)

The _ConsistentOneColumnResult [version](https://github.com/microsoft/Power-Fx/blob/main/src/tests/Microsoft.PowerFx.Core.Tests/ExpressionTestCases/TableStringFuncs_ConsistentOneColumnTableResult.txt) already exists. This PR just moves the existing tabular test cases to their own file.

**Review by CarlosFigueiraMSFT — APPROVED** [review]
:shipit:

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request merged**
