### PR TITLE
Make RecordValue.TryGetFieldAsync public

### PR DESCRIPTION
**Pull request by LucGenetier**
This will allow to implement ColumnMapRecordValue in Dataverse repo

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by MikeStall** [comment]
The liability is that we're enabling a new public entry point that circumvents checks. 

We have other patterns that use Composition over RecordValue. How do they accomplish it without this, and can we use that pattern? For example:
https://github.com/microsoft/Power-Fx/blob/main/src/libraries/Microsoft.PowerFx.Core/Public/Values/CompileTimeTypeWrapperTableValue.cs

**Pull request closed without merging**
