### PR TITLE
Enable UDF in REPL

### PR DESCRIPTION
**Pull request by adithyaselv**
Adds ability to define User-defined functions in REPL.

image

### CODE REVIEW

**Comment by gregli-msft** [comment]
Please fix https://github.com/microsoft/Power-Fx/issues/2545 and https://github.com/microsoft/Power-Fx/issues/2546 before merging.  Thanks!

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by adithyaselv** [comment]
Closing as this branch is having codeflow issue

**Comment by LucGenetier** [comment]
✅ No public API change.

**Pull request closed without merging**
