### PR TITLE
Updates to REPL

### PR DESCRIPTION
**Pull request by gregli-msft**
Fixes for:
- https://github.com/microsoft/Power-Fx/issues/1994
- https://github.com/microsoft/Power-Fx/issues/1983
- https://github.com/microsoft/Power-Fx/issues/1944
- https://github.com/microsoft/Power-Fx/issues/1943
- https://github.com/microsoft/Power-Fx/issues/1942
- https://github.com/microsoft/Power-Fx/issues/2013

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Review by MikeStall — APPROVED** [review]
:shipit:

**Pull request merged**
