### PR TITLE
Consistent Enum list, prep for strongly typed enum params

### PR DESCRIPTION
**Pull request by gregli-msft**
We have two places that enums are defined today, in BuiltInEnums.cs and EnumStoreBuilder.cs.  This change unifies them in preperation for adding additional metadata about each enum.  Additional helper functions are also added, completing support for number, boolean, string, and color.

### CODE REVIEW

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by LucGenetier** [comment]
✅ No public API change.

**Comment by gregli-msft** [comment]
Absorbed in larger strongly typed option set update.

**Pull request closed without merging**
